apiVersion: apps/v1
kind: Deployment
metadata:
  name: harc
  labels:
    app: harc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harc
  template:
    metadata:
      labels:
        app: harc
    spec:
      containers:
        - name: harc
          image: hvdevsecops.azurecr.io/vulnapp:110
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      imagePullSecrets:
      - name: mysecret
---
apiVersion: v1
kind: Service
metadata:
  name: harc
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: harc